# Generated by Django 4.2.3 on 2023-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
    ]
